name: Amaysim Web Automation Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: 
    inputs: 
      environment: 
        description: "Which environment to run tests against" 
        required: true 
        default: "PROD"
        type: choice 
        options: 
          - prod 
          - sit 
          - stg 
          - uat

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      PROD_URL: ${{ vars.PROD_URL }} 
      SIT_URL: ${{ vars.SIT_URL }}
      STG_URL: ${{ vars.STG_URL }} 
      UAT_URL: ${{ vars.UAT_URL }} 
      FIRST_NAME: ${{ vars.FIRST_NAME }} 
      LAST_NAME: ${{ vars.LAST_NAME }} 
      EMAIL_ADDRESS: ${{ vars.EMAIL_ADDRESS }} 
      DATE_OF_BIRTH: ${{ vars.DATE_OF_BIRTH }} 
      ADDRESS: ${{ vars.ADDRESS }} 
      PASSWORD: ${{ vars.PASSWORD }} 
      CONTACT_NUMBER: ${{ vars.CONTACT_NUMBER }} 
      INVALID_CARD_NUMBER: ${{ vars.INVALID_CARD_NUMBER }} 
      EXPIRATION_DATE: ${{ vars.EXPIRATION_DATE }} 
      CVV: ${{ vars.CVV }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.18.1'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run ${{ github.event.inputs.environment }}

    - name: Upload reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: cucumber-report
        path: ./report/amaysim-web-report
